PUT http://localhost:3003/api/blogs/6898c64855f8c3eaf7b3cea5
Content-Type: application/json

{
    "title": "How to train your horse",
    "author": "Cowboy",
    "url": "www.yeehaw.com",
    "likes": 6
}