POST http://localhost:3000/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdHRpQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3NjUwNDIyNDl9.BQGa2U5GKH1d8mq_CUTHPA2VQSKIgUht7L8T4ymv3eg

{
    "title": "Mun neljäs auto oli taas wolks vagen",
    "author": "Faija",
    "url": "www.abc.com",
    "likes": 11,
    "year": 2010
}