POST http://localhost:3000/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdHRpQGdtYWlsLmNvbSIsImlkIjoyLCJpYXQiOjE3NjQ3MDAzOTJ9.Fx_15OVevOiHFsZrXVBNbbO-XMmtV6hWSLJm-xl5FEA

{
    "title": "Mun eka auto oli saab",
    "author": "Faija",
    "url": "www.abc.com",
    "likes": 10,
    "year": 1994
}