POST http://localhost:3000/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5lbGxpQGdtYWlsLmNvbSIsImlkIjoyLCJpYXQiOjE3NjQ1MDYzNjR9.Um3sU_eU7eC8Wy0pg3GLeRQ2IwTsb_XWPL2In5aDez0

{
    "title": "This is working!!!",
    "author": "Happy Girl",
    "url": "www.hg.com",
    "likes": 3
}