POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hc2EiLCJpZCI6IjY4YTFiNGRjYjhmMjM5ZTJmOGFhZDUzMyIsImlhdCI6MTc1NTQzMDYzOH0.xxHRHi7UjWi8JC5Sq8O_fwlfBXYOp-6GIBhmkBTmZhs

{
    "title": "Kakku resepti",
    "author": "Katariina Kakku",
    "url": "www.kakku.fi",
    "likes": 4
}